version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: rodrigo
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nimbus_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
